# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3c3b11e373f22dd976153f8042667afcd93d38b96d2d462ffe950e309f2cc81c4407fa0f562d1f3b7cf1d494de9f3fd6b28eaf317caf0fa33f328575f04121b

test:
  secret_key_base: f13afc74d671bf26b4aee4f823d36fa1446e7acbcf12a747f3a46928b4907f6c2270ffa6b5cf348a4d5f16954e5e5d4997b1c8b6872d33befef8269d7dc46c4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
